hero_image: images/paint-box.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Caja de Lápices
description: Aprende a crear tu propio programa de pintura.
original_url: https://projects.raspberrypi.org/en/projects/paint-box
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Crear un lápiz
- title: Lápices de colores
- title: Cometer errores
- title: Cambiar el grosor del lápiz
- title: "Desafío: Accesos directos"
- title: "Desafío: Más lápices"

