hero_image: images/paint-box.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Farbkasten
description: In diesem Projekt wirst Du Dein eigenes Zeichen-Programm entwickeln!
original_url: https://projects.raspberrypi.org/en/projects/paint-box
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Einführung
- title: Einen Bleistift entwerfen
- title: Farbige Stifte
- title: Fehler machen
- title: Die Stift-Dicke ändern
- title: "Herausforderung: Tastenkürzel"
- title: "Herausforderung: Mehr Stifte"

