---
hero_image: images / banner.png
theme: vijolična
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: ustvarjalec, design-0, programiranje-2, fiz-comp-0, izdelava-0, skupnost-0
title: Paint Box
description: Naučite se, kako narediti svoj program barv.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: 'umetnost in oblikovanje'
technologies: praska
site_areas: kodeklub, praska
steps:
  - 
    title: Uvod
  - 
    title: Kaj boste potrebovali
  - 
    title: Izdelava svinčnika
  - 
    title: Barvni svinčniki
  - 
    title: Napake
  - 
    title: Spreminjanje širine svinčnika
  - 
    title: 'Izziv: bližnjice'
  - 
    title: 'Izziv: več svinčnikov'
